### ISSUE TITLE
No such file or directory: 'gaussian_fit.pt'

### ISSUE THREAD

**Issue by Victor-QTP** [ffhibnese/GIFD#1]
Hi!
I find your work to be very interesting, 
As I tried to reproduce the result from the given code, I encountered the following error:
_FileNotFoundError: [Errno 2] No such file or directory: 'gaussian_fit.pt'_
It seems like the file is missing from the repo, could you please upload it?

PS
I run: _python3 rec_mult.py --config configs_stylegan2.yml_

**Comment by ffhibnese** [comment]
Thanks for your comment! The file 'gaussian_fit.pt' is actually the mentioned shape_predictor downloaded by the provided instruction. Feel free to contact me if you have any further question.

**Comment by Victor-QTP** [comment]
I understand, thank you for the reply!
